apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 21.0.6
    helm:
      releaseName: nginx1
      values: |
        service:
          type: LoadBalancer
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true