apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-infra
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/Jojoooo1/argo-deploy-gke-infra.git
    targetRevision: main
    path: argo-apps/overlays/dev
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: dev
        - name: PROJECT
          value: "<your-gcp-dev-service-id>"

        - name: DNS_PROJECT_ID
          value: "<your-gcp-dns-service-id>"
        - name: DNS_DOMAIN
          value: "<your-domain.com>"
        - name: DNS_ENV
          value: '-dev'

        - name: CLUSTER
          value: "<your-cluster-id>"
        - name: CLUSTER_LOCATION
          value: "us-east1-b"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd