apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      release: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        release: frontend
    spec:
      containers:
        - name: frontend-container
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi" 
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"