apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.4
    helm:
      values: |
        provider: azure
        azure.resourceGroup: "rg-aks-demo"
        azure.subscriptionId: "3f6a7dd6-0892-469a-9550-8d67f5447178"
        azure.tenantId: "916b08d4-1ccd-4de2-9379-67f415724dba"
        azure.aadClientId: "ea5b1463-7f43-40aa-bcf9-bc5a3adfbc8c"
        azure.aadClientSecret: "<client-secret>"
        domainFilters:
          - "urossimeunovic.com"
        policy: sync
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true